# for cmake build
name: bnb
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - pip
  - pip:
    - --index-url https://download.pytorch.org/whl/nightly/cu121
    - --pre
    - torch==2.6.0.dev20241112+cu121
  - python
  #- accelerate
  #- einops
  - scipy
  #- transformers
  - pytest
  - pytest-cases
  - ipython
  - debugpy
  - yapf
  - monkeytype
  - rich
  - pytest-sugar
